require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "react-native-hinge"
  s.module_name  = "Hinge"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = "https://github.com/tumerorkun/react-native-hinge"
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => "15.0" }
  s.source       = { :git => "https://github.com/tumerorkun/react-native-hinge.git", :tag => "#{s.version}" }

  s.source_files = "ios/**/*.{h,m,mm,swift}"

  # Add all files generated by Nitrogen
  load 'nitrogen/generated/ios/Hinge+autolinking.rb'
  add_nitrogen_files(s)
end
